<?xml version="1.0" encoding="iso-8859-1" ?>
<!-- $Revision:$ -->

<refentry id="{@id}.intro">
<refnamediv>
    <refname>Introduction</refname>
    <refpurpose>
        Cgiapp2 is a PHP port of the Perl module CGI::Application. Its purpose is
        to serve as a framework for creating extensible, reusable web
        applications.
    </refpurpose>
</refnamediv>

<refsect1 id="{@id}.intro.desc">
    <title>Description</title>
    <para>
        <classname>Cgiapp2</classname> is intended to make it easier to create
        sophisticated, reusable web-based applications.  This module implements
        a methodology which, if followed, will make your web software easier to
        design, easier to document, easier to write, and easier to evolve.
    </para>

    <para>
        Cgiapp2 builds on standard, non-proprietary technologies and techniques,
        such as PHP and Smarty.  Like its perl ancestor, Cgiapp2 judiciously
        avoids employing technologies and techniques which would bind a
        developer to any one set of tools, operating system or web server.
    </para>
</refsect1>
</refentry>
<!-- Keep this comment at the end of the file
Local variables:
mode: sgml
sgml-omittag:t
sgml-shorttag:t
sgml-minimize-attributes:nil
sgml-always-quote-attributes:t
sgml-indent-step:1
sgml-indent-data:t
sgml-parent-document:nil
sgml-default-dtd-file:"../../../../../manual.ced"
sgml-exposed-tags:nil
sgml-local-catalogs:nil
sgml-local-ecat-files:nil
End:
vim: ft=xml:
-->
