<?xml version="1.0" encoding="iso-8859-1" ?>
<!-- $Revision:$ -->

<refentry id="{@id}.resources">
<refnamediv>
  <refname>Resources and Credits</refname>
</refnamediv>

<refsect1 id="{@id}.resources.references">
   <title>Resources</title>
    <itemizedlist>
        <listitem>{@link http://www.php.net PHP}, </listitem>
        <listitem>{@link http://smarty.php.net Smarty Template Engine},</listitem>
        <listitem>{@link http://search.cpan.org/search?query=CGI%3A%3AApplication CGI::Application},</listitem>
        <listitem>{@link http://www.perl.com perl}</listitem>
    </itemizedlist>
</refsect1>

<refsect1 id="{@id}.resources.reading">
    <title>More Reading</title>
    <para>
        If you're interested in finding out more about CGI::Application, on
        which Cgiapp2 is based, the following article is available on Perl.com:
        {@link http://www.perl.com/pub/a/2001/06/05/cgi.html Using CGI::Application}
    </para>
</refsect1>

<refsect1 id="{@id}.resources.credits">
    <title>Credits</title>
    <para>
        Thank you to Jesse Erlbaum for reviewing the initial release of this
        class and approving my release of it to the greater PHP programming
        community. Thank you as well to the CGI::Application mailing lists for
        many tips and pointers (though I've only been lurking), and to the
        CGI::Application development team for continuing work on that
        excellent perl module.
    </para>

    <para>
        Several people have greatly improved my understanding of PHP, design
        patterns, and PHP's OOP model. Thanks go in particular to Paul M.
        Jones and Mike Naberezny.
    </para>

    <para>
        Thanks also go to my former employer, the National Gardening
        Association, for allowing me the time to port CGI::Application to PHP
        in order to make my work easier; in particular, many thanks to my
        then-IT Manager, Rob Riggen, for his support.
    </para>
</refsect1>

<refsect1 id="{@id}.resources.license">
    <title>License</title>
    <para>
        Cgiapp2.class.php : Framework for building reusable PHP web applications.
        Copyright (C) 2004 - present Matthew Weier O'Phinney
        &lt;mweierophinney@gmail.com&gt;.
    </para>

    <para>
        Cgiapp2 and the libraries with which it is distributed are licensed
        under 
        {@link http://www.opensource.org/licenses/bsd-license.php the BSD License}.
        As such, you may redistribute them in accordance with that license.
    </para>
</refsect1>

</refentry>
<!-- Keep this comment at the end of the file
Local variables:
mode: sgml
sgml-omittag:t
sgml-shorttag:t
sgml-minimize-attributes:nil
sgml-always-quote-attributes:t
sgml-indent-step:1
sgml-indent-data:t
sgml-parent-document:nil
sgml-default-dtd-file:"../../../../../manual.ced"
sgml-exposed-tags:nil
sgml-local-catalogs:nil
sgml-local-ecat-files:nil
End:
vim600: syn=xml fen fdm=syntax fdl=2 si
vim: et tw=78 syn=sgml
vi: ts=1 sw=1
-->
